@startuml
hide empty description
scale max 800 width

<style>
stateDiagram {
  LineColor black
}
</style>

skinparam state {
  BackgroundColor #white
  BackgroundColor<<LongTime>> #9F9
  BorderColor #black
}

Title Клиентское приложение

state ClientServiceApp {

state WaitConnectedEvent <<LongTime>>
state SendInitInfoToRouter <<LongTime>>
state WaitEvents <<LongTime>>
state WaitDisconnectedEvent <<LongTime>>

[*] -[#blue]-> LoadLocalSettings : start

LoadLocalSettings -[#red]-> [*] : error
LoadLocalSettings -[#green]-> PreparingForConnectToRouter : ok

PreparingForConnectToRouter -[#red]-> [*] : error
PreparingForConnectToRouter -[#green]-> WaitConnectedEvent : ok

WaitConnectedEvent -[#green]-> SendInitInfoToRouter : connected
WaitConnectedEvent -[#blue]-> [*] : stop

SendInitInfoToRouter -[#green]-> WaitEvents : ok
SendInitInfoToRouter -up[#red]-> Disconnect : error
SendInitInfoToRouter -[#green]-> SendInitInfoToRouter : new_msg

Disconnect -up-> WaitDisconnectedEvent : ok

WaitDisconnectedEvent -up-> PreparingForConnectToRouter : disconnected

WaitEvents -[#red]-> PreparingForConnectToRouter : disconnected
WaitEvents -[#blue]-> [*] : stop
WaitEvents -[#green]-> ProcessMsg : new_msg

ProcessMsg -[#green]-> WaitEvents : ok
ProcessMsg -[#red]-> WaitEvents : error
}
@enduml
