@startuml
hide empty description
scale max 800 width

<style>
stateDiagram {
  LineColor black
}
</style>

skinparam state {
  BackgroundColor #white
  BackgroundColor<<LongTime>> #9F9
  BorderColor #black
}

Title Преобразование получаемых данных по TCP в сообщения

state InMsgProcessing {

state WaitMsg <<LongTime>>
state ApplyServiceCommand <<choise>>

[*] -[#green]-> WaitMsg : start

TryGetMsqFromQueue --> WaitMsg : no_msg
TryGetMsqFromQueue -[#green]-> CheckMsgType : msg

WaitMsg -[#green]-> [*] : stop
WaitMsg -[#green]-> TryGetMsqFromQueue : timeout

CheckMsgType -[#red]-> IgnoreMsg : unknown
CheckMsgType --> ApplyConnectionCommand : msg_for_connection
CheckMsgType -[#green]-> DetermineService : msg_for_service

IgnoreMsg --> TryGetMsqFromQueue : ok

ApplyConnectionCommand -[#red]->IgnoreMsg : error
ApplyConnectionCommand --> TryGetMsqFromQueue : ok

DetermineService -[#red]-> IgnoreMsg : no_service_found
DetermineService -[#green]-> ApplyServiceCommand : service_found

ApplyServiceCommand -[#red]->IgnoreMsg : error
ApplyServiceCommand -[#green]-> TryGetMsqFromQueue : ok


}
@enduml
