@startuml
hide empty description
scale max 800 width

Title Преобразование получаемых данных по TCP в сообщения

state InDataProcessing {
[*] --> ОжиданиеВходящихДанных : start
ОжиданиеВходящихДанных --> БуферизацияВходящихДанных : new_data
ОжиданиеВходящихДанных --> [*] : stop\nerror
БуферизацияВходящихДанных --> [*] : error
БуферизацияВходящихДанных --> ПопыткаИзвлеченияСообщения : ok
ПопыткаИзвлеченияСообщения --> ВыбросСообщения : new_msg
ПопыткаИзвлеченияСообщения --> ОжиданиеВходящихДанных : no_full_msg
ВыбросСообщения --> ПопыткаИзвлеченияСообщения : ok
}
@enduml
